
image:
 file: .gitpod.Dockerfile

tasks:
 - init: |
      pnpm install
      pnpm db:push && pnpm db:seed
   command: 
      npx prisma generate --schema=./apps/api/prisma/schema.prisma
      npx prisma migrate dev --schema=./apps/api/prisma/schema.prisma
      pnpm dev

ports:
  - port: 3001
    visibility: public
  - port: 3000
    visibility: public

vscode:
  extensions:
    - svelte.svelte-vscode-nightly
    - ms-azuretools.vscode-docker
    - Prisma.prisma
